name: Add new issues to js-waku project board

on:
  issues:
    types: [opened]

jobs:
  add-new-issue-to-new-column:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          project: js-waku
          column: New
          repo-token: ${{ secrets.GH_ACTION_PROJECT_MGMT }}
